In [17]:
import pandas as pd

In [18]:
game_diff = pd.read_csv("game_difference.csv")

In [19]:
game_diff

,Unnamed: 0,YEAR,ROUND,WSEED,WTEAM,WSCORE,LSEED,LTEAM,LSCORE,SCORE_DIFF,...,ORB,DRB,FTR,FTRD,X2P_O,X2P_D,X3P_O,X3P_D,ADJ_T,WAB
0,1,2013,1,11,Minnesota,83,6,UCLA,63,-20,...,-12.9,0.8,-8.5,-12.1,0.1,4.1,-0.4,-1.5,5.5,1.2
1,2,2013,1,8,Colorado State,84,9,Missouri,72,12,...,2.7,-5.4,9.1,6.7,-3.0,3.0,0.2,0.9,-2.9,0.7
2,3,2013,1,12,Mississippi,57,5,Wisconsin,46,-11,...,-1.5,-4.9,-9.1,-5.4,-1.4,-3.4,0.6,-2.4,-9.0,3.0
3,4,2013,1,4,Michigan,71,13,South Dakota State,56,15,...,3.6,3.3,-4.6,-1.7,3.0,-2.2,-1.0,-3.2,0.8,9.4
4,5,2013,1,6,Butler,68,11,Bucknell,56,12,...,6.6,2.0,2.7,6.7,1.9,4.2,-1.5,2.7,1.3,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,379,2021,2,1,Michigan,86,8,LSU,78,8,...,-2.1,-8.0,-5.0,-4.6,0.3,-9.0,3.7,3.5,-3.5,4.8
379,380,2021,2,7,Oregon,95,2,Iowa,80,-15,...,2.4,1.4,5.2,-4.5,-0.5,-4.1,0.7,1.2,2.8,2.6
380,381,2021,2,6,USC,85,3,Kansas,51,-34,...,-4.8,-0.4,-7.0,1.7,-2.8,3.7,-1.0,-1.6,1.0,0.6
381,382,2021,2,5,Creighton,72,13,Ohio,58,14,...,-3.9,0.8,-2.7,-4.5,-0.1,-5.5,0.1,-1.6,-0.2,5.5
382,383,2021,2,1,Gonzaga,87,8,Oklahoma,71,16,...,3.1,-4.1,7.6,3.1,13.2,0.5,2.7,-2.9,7.0,8.2

In [20]:
game_copy = game_diff.copy()

In [21]:
game_copy

,Unnamed: 0,YEAR,ROUND,WSEED,WTEAM,WSCORE,LSEED,LTEAM,LSCORE,SCORE_DIFF,...,ORB,DRB,FTR,FTRD,X2P_O,X2P_D,X3P_O,X3P_D,ADJ_T,WAB
0,1,2013,1,11,Minnesota,83,6,UCLA,63,-20,...,-12.9,0.8,-8.5,-12.1,0.1,4.1,-0.4,-1.5,5.5,1.2
1,2,2013,1,8,Colorado State,84,9,Missouri,72,12,...,2.7,-5.4,9.1,6.7,-3.0,3.0,0.2,0.9,-2.9,0.7
2,3,2013,1,12,Mississippi,57,5,Wisconsin,46,-11,...,-1.5,-4.9,-9.1,-5.4,-1.4,-3.4,0.6,-2.4,-9.0,3.0
3,4,2013,1,4,Michigan,71,13,South Dakota State,56,15,...,3.6,3.3,-4.6,-1.7,3.0,-2.2,-1.0,-3.2,0.8,9.4
4,5,2013,1,6,Butler,68,11,Bucknell,56,12,...,6.6,2.0,2.7,6.7,1.9,4.2,-1.5,2.7,1.3,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,379,2021,2,1,Michigan,86,8,LSU,78,8,...,-2.1,-8.0,-5.0,-4.6,0.3,-9.0,3.7,3.5,-3.5,4.8
379,380,2021,2,7,Oregon,95,2,Iowa,80,-15,...,2.4,1.4,5.2,-4.5,-0.5,-4.1,0.7,1.2,2.8,2.6
380,381,2021,2,6,USC,85,3,Kansas,51,-34,...,-4.8,-0.4,-7.0,1.7,-2.8,3.7,-1.0,-1.6,1.0,0.6
381,382,2021,2,5,Creighton,72,13,Ohio,58,14,...,-3.9,0.8,-2.7,-4.5,-0.1,-5.5,0.1,-1.6,-0.2,5.5
382,383,2021,2,1,Gonzaga,87,8,Oklahoma,71,16,...,3.1,-4.1,7.6,3.1,13.2,0.5,2.7,-2.9,7.0,8.2

In [22]:
for ind, row in game_copy.iterrows():
    if game_copy.loc[ind,"SCORE_DIFF"] < 0:
        game_copy.loc[ind,"upset"] = 1
    else:
        game_copy.loc[ind,"upset"] = 0

In [23]:
for ind,row in game_copy.iterrows():
    if game_copy.loc[ind,"WSEED"] < game_copy.loc[ind,"LSEED"]:
        game_copy.loc[ind,"HSEED"] = game_copy.loc[ind,"WSEED"]
        game_copy.loc[ind,"LSEED"] = game_copy.loc[ind,"LSEED"]
        game_copy.loc[ind,"HTEAM"] = game_copy.loc[ind,"WTEAM"]
        game_copy.loc[ind,"LTEAM"] = game_copy.loc[ind,"LTEAM"]
        game_copy.loc[ind,"HSCORE"] = game_copy.loc[ind,"WSCORE"]
        game_copy.loc[ind,"LSCORE"] = game_copy.loc[ind,"LSCORE"]
    elif game_copy.loc[ind,"LSEED"] < game_copy.loc[ind,"WSEED"]:
        game_copy.loc[ind,"HSEED"] = game_copy.loc[ind,"LSEED"]
        game_copy.loc[ind,"LSEED"] = game_copy.loc[ind,"WSEED"]
        game_copy.loc[ind,"HTEAM"] = game_copy.loc[ind,"LTEAM"]
        game_copy.loc[ind,"LTEAM"] = game_copy.loc[ind,"WTEAM"]
        game_copy.loc[ind,"HSCORE"] = game_copy.loc[ind,"LSCORE"]
        game_copy.loc[ind,"LSCORE"] = game_copy.loc[ind,"HSCORE"]

In [24]:
game_copy

,Unnamed: 0,YEAR,ROUND,WSEED,WTEAM,WSCORE,LSEED,LTEAM,LSCORE,SCORE_DIFF,...,X2P_O,X2P_D,X3P_O,X3P_D,ADJ_T,WAB,upset,HSEED,HTEAM,HSCORE
0,1,2013,1,11,Minnesota,83,11,Minnesota,63,-20,...,0.1,4.1,-0.4,-1.5,5.5,1.2,1.0,6.0,UCLA,63.0
1,2,2013,1,8,Colorado State,84,9,Missouri,72,12,...,-3.0,3.0,0.2,0.9,-2.9,0.7,0.0,8.0,Colorado State,84.0
2,3,2013,1,12,Mississippi,57,12,Mississippi,46,-11,...,-1.4,-3.4,0.6,-2.4,-9.0,3.0,1.0,5.0,Wisconsin,46.0
3,4,2013,1,4,Michigan,71,13,South Dakota State,56,15,...,3.0,-2.2,-1.0,-3.2,0.8,9.4,0.0,4.0,Michigan,71.0
4,5,2013,1,6,Butler,68,11,Bucknell,56,12,...,1.9,4.2,-1.5,2.7,1.3,3.7,0.0,6.0,Butler,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,379,2021,2,1,Michigan,86,8,LSU,78,8,...,0.3,-9.0,3.7,3.5,-3.5,4.8,0.0,1.0,Michigan,86.0
379,380,2021,2,7,Oregon,95,7,Oregon,80,-15,...,-0.5,-4.1,0.7,1.2,2.8,2.6,1.0,2.0,Iowa,80.0
380,381,2021,2,6,USC,85,6,USC,51,-34,...,-2.8,3.7,-1.0,-1.6,1.0,0.6,1.0,3.0,Kansas,51.0
381,382,2021,2,5,Creighton,72,13,Ohio,58,14,...,-0.1,-5.5,0.1,-1.6,-0.2,5.5,0.0,5.0,Creighton,72.0
382,383,2021,2,1,Gonzaga,87,8,Oklahoma,71,16,...,13.2,0.5,2.7,-2.9,7.0,8.2,0.0,1.0,Gonzaga,87.0

In [ ]:
import numpy as np

In [25]:
game_copy = game_copy.drop(["WSEED","WTEAM","WSCORE","Unnamed: 0"], axis=1)

In [26]:
game_copy.to_csv('upset_data.csv')

In [ ]:
game_copy

In [27]:

r1_22 = pd.read_csv("r1games_2022.csv")

In [28]:
game_copy.shape

(383, 31)

In [34]:
r1_22 = r1_22.drop(["Unnamed: 0"], axis = 1)

In [35]:
full_data = pd.concat([game_copy,r1_22], ignore_index= True)

In [36]:
full_data.to_csv('full_22_data.csv')

In [37]:
full_data

,YEAR,ROUND,LSEED,LTEAM,LSCORE,SCORE_DIFF,confW,confL,G,W,...,X2P_D,X3P_O,X3P_D,ADJ_T,WAB,upset,HSEED,HTEAM,HSCORE,UPSET
0,2013,1,11,Minnesota,63,-20,B10,P12,1,4,...,4.1,-0.4,-1.5,5.5,1.2,1.0,6.0,UCLA,63.0,NaN
1,2013,1,9,Missouri,72,12,MWC,SEC,-1,1,...,3.0,0.2,0.9,-2.9,0.7,0.0,8.0,Colorado State,84.0,NaN
2,2013,1,12,Mississippi,46,-11,SEC,B10,-1,-4,...,-3.4,0.6,-2.4,-9.0,3.0,1.0,5.0,Wisconsin,46.0,NaN
3,2013,1,13,South Dakota State,56,15,B10,Sum,6,8,...,-2.2,-1.0,-3.2,0.8,9.4,0.0,4.0,Michigan,71.0,NaN
4,2013,1,11,Bucknell,56,12,A10,Pat,2,-1,...,4.2,-1.5,2.7,1.3,3.7,0.0,6.0,Butler,68.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,2022,1,10,Miami FL,68,-2,NaN,NaN,0,3,...,-12.3,0.1,-1.5,-1.4,1.5,NaN,7.0,USC,66.0,1.0
411,2022,1,9,Memphis,64,-11,NaN,NaN,2,5,...,2.7,-1.8,0.3,-5.8,2.1,NaN,8.0,Boise State,53.0,1.0
412,2022,1,9,Marquette,63,32,NaN,NaN,2,5,...,2.1,1.5,3.2,-0.9,3.7,NaN,8.0,North Carolina,95.0,0.0
413,2022,1,9,TCU,69,-27,NaN,NaN,-2,0,...,-3.1,3.0,-0.5,1.7,-1.0,NaN,8.0,Seton Hall,42.0,1.0
414,2022,1,9,Creighton,72,-3,NaN,NaN,-2,1,...,-0.4,5.1,-1.3,-1.7,0.9,NaN,8.0,San Diego State,69.0,1.0